### PR TITLE
Add workaround to make text widget input work with submit button on Android Chrome's default keyboard (Gboard)

### PR DESCRIPTION
**Pull request by shaunkrd**
This change replaces v-model in the text widget's input with the longhand equivalent (value binding and v-on:input).

This change fixes an issue where the widget's submit button doesn't become enabled after typing characters into the input. The `v-model` isn't updating the field's data value as normal characters are typed.

The issue is explained here:

[https://github.com/vuejs/vue/issues/9777]
(https://github.com/vuejs/vue/issues/9777)

and a comment from Evan You:

[https://github.com/vuejs/vue/issues/9777#issuecomment-478831263](https://github.com/vuejs/vue/issues/9777#issuecomment-478831263)

Replacing the `v-model` with a custom @input/:value pair as suggested by Evan fixes the issue when using Gboard, without impacting the behaviour on other devices.

### CODE REVIEW

**Comment by andypattenden** [comment]
Only thing I would add here is a code comment explaining the reason for not using `v-model` and referencing the comment in the Github issue.

**Comment by alexrussell** [comment]
FWIW it's not an issue per se. In fact it's 100% by design.

It's just when a given keyboard is in composing mode the stuff the person types isn't actually "committed" yet until space or some other non-word character, so that's thy `v-model` doesn't update. And it is documented: https://vuejs.org/v2/guide/forms.html#vmodel-ime-tip

That said, it looks like they are trying to push through a [`v-model.eager` modifier[(https://github.com/vuejs/vue/pull/9814) to allow people to still use `v-model` for all its other benefits but telling it to always respond to keypresses even if composing.

**Comment by nicksnell** [comment]
So this looks acceptable.... but I guess the question is really _should_ we being doing this? does it break Gboard usage expectations?

**Comment by alexrussell** [comment]
Along the same lines, if the user is *actually* using the composition feature of the keyboard (e.g. pinyin) this will start to "set the value" as they are trying to compose words.

I don't know exactly how this might affect anything (it may not - composing may still work, and after each "commit" the value will be right) and realistically how many instances of this "issue" is people actually seeing a problem while they are *actually* trying to compose, as opposed to where the keyboard is in a kind of auto-compose mode that's not important?

**Comment by alexrussell** [comment]
As I said in my initial approval - I don't like this (it's hacking around something that's done on purpose), but not knowing the background of this work (looks like a disabled submit button isn't being set to enabled even though there is text "in" the input), presumably it's vital that the input is set as a person types to enable the button as some people expect to be able to press on the button while they're still composing, not knowing themselves that the keyboard is in some kind of composition mode.

**Pull request merged**
